import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

for (const config of nextVitals) {
  if (config.rules) {
    if (config.rules["react-hooks/purity"]) config.rules["react-hooks/purity"] = "warn";
    if (config.rules["react-hooks/set-state-in-effect"]) config.rules["react-hooks/set-state-in-effect"] = "warn";
  }
}

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    "node_modules/**",
    ".git/**",
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    "artifacts/**",
    ".cameraos-data/**",
    "apps/artifacts/**",
    ".opencode/**",
    ".codegraph/**",
    ".tempmediaStorage/**",
    // Generated MediaPipe WASM/runtime assets are vendor files.
    "public/mediapipe/**",
    // Archived/reference docs app is not part of the active WindowMini workspace validation.
    "docs/**",
    // Desktop renderer production output is generated by Vite.
    "apps/desktop/renderer/dist/**",
    "apps/desktop/electron/main/camera/canon/bin/**",
  ]),
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": "warn",
      "@next/next/no-img-element": "warn",
    },
  },
  {
    files: ["**/*.cjs"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
]);

export default eslintConfig;
