import type { FrameConfig } from "@/types/theme";

export const frameConfigs = [
    // --- 1 SHOT FRAMES (1800x1200 & 1200x1800) ---
    {
        id: "white-border-1shot-landscape",
        name: "1 Ô Ngang - Khung Trắng (1800x1200)",
        description: "Khung trắng 1 ô ảnh khổ ngang 1800x1200.",
        borderColor: "#ffffff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 1,
        photoViewportOrientation: "landscape",
        layoutFamily: "single",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "white-border-1shot-portrait",
        name: "1 Ô Dọc - Khung Trắng (1200x1800)",
        description: "Khung trắng 1 ô ảnh khổ dọc 1200x1800.",
        borderColor: "#ffffff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 1,
        photoViewportOrientation: "portrait",
        layoutFamily: "single",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "single-landscape-gold",
        name: "1 Ô Ngang - Viền Vàng (1800x1200)",
        description: "Khung 1 ảnh đơn khổ ngang 1800x1200 sang trọng.",
        borderColor: "#facc15",
        borderWidth: 32,
        kind: "solid",
        shotCount: 1,
        photoViewportOrientation: "landscape",
        layoutFamily: "single",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "single-portrait-gold",
        name: "1 Ô Dọc - Viền Vàng (1200x1800)",
        description: "Khung 1 ảnh đơn khổ dọc 1200x1800 sang trọng.",
        borderColor: "#facc15",
        borderWidth: 32,
        kind: "solid",
        shotCount: 1,
        photoViewportOrientation: "portrait",
        layoutFamily: "single",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "single-landscape-girly",
        name: "1 Ô Ngang - Girly Pink (1800x1200)",
        description: "Khung 1 ảnh đơn khổ ngang 1800x1200 dễ thương.",
        borderColor: "#fbcfe8",
        borderWidth: 34,
        kind: "solid",
        shotCount: 1,
        photoViewportOrientation: "landscape",
        layoutFamily: "single",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "single-portrait-girly",
        name: "1 Ô Dọc - Girly Pink (1200x1800)",
        description: "Khung 1 ảnh đơn khổ dọc 1200x1800 dễ thương.",
        borderColor: "#fbcfe8",
        borderWidth: 34,
        kind: "solid",
        shotCount: 1,
        photoViewportOrientation: "portrait",
        layoutFamily: "single",
        outputWidth: 1200,
        outputHeight: 1800,
    },

    // --- 2 SHOT FRAMES (1800x1200 & 1200x1800) ---
    {
        id: "white-border-2shot-landscape",
        name: "2 Ô Ngang - Khung Trắng (1800x1200)",
        description: "Khung trắng 2 ô ảnh khổ ngang 1800x1200.",
        borderColor: "#ffffff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 2,
        photoViewportOrientation: "landscape",
        layoutFamily: "1x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "white-border-2shot-portrait",
        name: "2 Ô Dọc - Khung Trắng (1200x1800)",
        description: "Khung trắng 2 ô ảnh khổ dọc 1200x1800.",
        borderColor: "#ffffff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 2,
        photoViewportOrientation: "portrait",
        layoutFamily: "1x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "twin-landscape-2slot",
        name: "2 Ô Ngang - Twin Violet (1800x1200)",
        description: "Khung đôi 2 ô ảnh khổ ngang 1800x1200.",
        borderColor: "#e0e7ff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 2,
        photoViewportOrientation: "landscape",
        layoutFamily: "1x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "twin-portrait-2slot",
        name: "2 Ô Dọc - Twin Violet (1200x1800)",
        description: "Khung đôi 2 ô ảnh khổ dọc 1200x1800.",
        borderColor: "#e0e7ff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 2,
        photoViewportOrientation: "portrait",
        layoutFamily: "1x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "twin-landscape-girly",
        name: "2 Ô Ngang - Girly Pink (1800x1200)",
        description: "Khung đôi 2 ô ảnh màu hồng xinh xắn.",
        borderColor: "#fbcfe8",
        borderWidth: 32,
        kind: "solid",
        shotCount: 2,
        photoViewportOrientation: "landscape",
        layoutFamily: "1x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "twin-portrait-girly",
        name: "2 Ô Dọc - Girly Pink (1200x1800)",
        description: "Khung đôi 2 ô ảnh màu hồng khổ dọc.",
        borderColor: "#fbcfe8",
        borderWidth: 32,
        kind: "solid",
        shotCount: 2,
        photoViewportOrientation: "portrait",
        layoutFamily: "1x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },

    // --- 4 SHOT FRAMES (1800x1200 & 1200x1800) ---
    {
        id: "white-border",
        name: "4 Ô Ngang - Khung Trắng (1800x1200)",
        description: "Khung trắng 4 ô ảnh khổ ngang 1800x1200.",
        borderColor: "#ffffff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "white-border-portrait",
        name: "4 Ô Dọc - Khung Trắng (1200x1800)",
        description: "Khung trắng 4 ô ảnh khổ dọc 1200x1800.",
        borderColor: "#ffffff",
        borderWidth: 32,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "canva-placeholder",
        name: "4 Ô Dọc - Canva PNG Placeholder (1200x1800)",
        description: "Slot metadata cho khung Canva PNG 4 ô khổ dọc 1200x1800.",
        borderColor: "#fce7f3",
        borderWidth: 0,
        kind: "png-overlay",
        source: "canva",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "landscape-film-4slot",
        name: "4 Ô Ngang - Film Cổ Điển (1800x1200)",
        description: "Khung phim cổ điển 4 ô khổ ngang 1800x1200.",
        borderColor: "#1e1e24",
        borderWidth: 28,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "portrait-film-4slot",
        name: "4 Ô Dọc - Film Cổ Điển (1200x1800)",
        description: "Khung phim cổ điển 4 ô khổ dọc 1200x1800.",
        borderColor: "#1e1e24",
        borderWidth: 28,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "strip-landscape-1x4",
        name: "4 Ô Ngang - Dải Ảnh Strip (1800x1200)",
        description: "Khung dải ảnh dài 4 ô khổ ngang.",
        borderColor: "#f3e8ff",
        borderWidth: 24,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "1x4",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "strip-portrait-1x4",
        name: "4 Ô Dọc - Dải Ảnh Strip (1200x1800)",
        description: "Khung dải ảnh dài 4 ô khổ dọc photobooth Hàn Quốc.",
        borderColor: "#f3e8ff",
        borderWidth: 24,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "1x4",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "gold",
        name: "4 Ô Ngang - Viền Vàng (1800x1200)",
        description: "Khung viền vàng 4 ô khổ ngang 1800x1200.",
        borderColor: "#facc15",
        borderWidth: 32,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "gold-portrait",
        name: "4 Ô Dọc - Viền Vàng (1200x1800)",
        description: "Khung viền vàng 4 ô khổ dọc 1200x1800.",
        borderColor: "#facc15",
        borderWidth: 32,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "girly",
        name: "4 Ô Ngang - Girly Pink (1800x1200)",
        description: "Khung hồng phấn ngọt ngào dễ thương khổ ngang.",
        borderColor: "#fbcfe8",
        borderWidth: 34,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "girly-portrait",
        name: "4 Ô Dọc - Girly Pink (1200x1800)",
        description: "Khung hồng phấn ngọt ngào dễ thương khổ dọc.",
        borderColor: "#fbcfe8",
        borderWidth: 34,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "conan",
        name: "4 Ô Ngang - Conan Detective (1800x1200)",
        description: "Khung phong cách phá án kỳ bí khổ ngang.",
        borderColor: "#1e293b",
        borderWidth: 34,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "conan-portrait",
        name: "4 Ô Dọc - Conan Detective (1200x1800)",
        description: "Khung phong cách phá án kỳ bí khổ dọc.",
        borderColor: "#1e293b",
        borderWidth: 34,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "steven-universe",
        name: "4 Ô Ngang - Steven Universe (1800x1200)",
        description: "Khung vũ trụ lấp lánh rực rỡ khổ ngang.",
        borderColor: "#38bdf8",
        borderWidth: 30,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "steven-portrait",
        name: "4 Ô Dọc - Steven Universe (1200x1800)",
        description: "Khung vũ trụ lấp lánh rực rỡ khổ dọc.",
        borderColor: "#38bdf8",
        borderWidth: 30,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "tinder",
        name: "4 Ô Ngang - Tinder Match (1800x1200)",
        description: "Khung đỏ Tinder nóng bỏng khổ ngang.",
        borderColor: "#f43f5e",
        borderWidth: 30,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "tinder-portrait",
        name: "4 Ô Dọc - Tinder Match (1200x1800)",
        description: "Khung đỏ Tinder nóng bỏng khổ dọc.",
        borderColor: "#f43f5e",
        borderWidth: 30,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "matcha",
        name: "4 Ô Ngang - Matcha Tea (1800x1200)",
        description: "Khung xanh matcha nhẹ nhàng khổ ngang.",
        borderColor: "#d1fae5",
        borderWidth: 34,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x2",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "matcha-portrait",
        name: "4 Ô Dọc - Matcha Tea (1200x1800)",
        description: "Khung xanh matcha nhẹ nhàng khổ dọc.",
        borderColor: "#d1fae5",
        borderWidth: 34,
        kind: "solid",
        shotCount: 4,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x2",
        outputWidth: 1200,
        outputHeight: 1800,
    },

    // --- 6 SHOT FRAMES (1800x1200 & 1200x1800) ---
    {
        id: "white-border-6shot-landscape",
        name: "6 Ô Ngang - Khung Trắng (1800x1200)",
        description: "Khung trắng 6 ô ảnh khổ ngang 1800x1200.",
        borderColor: "#ffffff",
        borderWidth: 28,
        kind: "solid",
        shotCount: 6,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x3",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "white-border-6shot-portrait",
        name: "6 Ô Dọc - Khung Trắng (1200x1800)",
        description: "Khung trắng 6 ô ảnh khổ dọc 1200x1800.",
        borderColor: "#ffffff",
        borderWidth: 28,
        kind: "solid",
        shotCount: 6,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x3",
        outputWidth: 1200,
        outputHeight: 1800,
    },
    {
        id: "canva-bunny-6slot",
        name: "6 Ô Ngang - Canva Bunny (1800x1200)",
        description: "Khung Canva 6 ô ảnh phong cách thỏ hồng xinh xắn khổ ngang.",
        borderColor: "#fce7f3",
        borderWidth: 0,
        kind: "png-overlay",
        source: "canva",
        shotCount: 6,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x3",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "six-portrait-bunny",
        name: "6 Ô Dọc - Canva Bunny (1200x1800)",
        description: "Khung Canva 6 ô ảnh phong cách thỏ hồng xinh xắn khổ dọc.",
        borderColor: "#fce7f3",
        borderWidth: 0,
        kind: "png-overlay",
        source: "canva",
        shotCount: 6,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x3",
        outputWidth: 1200,
        outputHeight: 1800,
    },

    // --- 8 SHOT FRAMES (1800x1200 & 1200x1800) ---
    {
        id: "eight-landscape-grid",
        name: "8 Ô Ngang - Grid Trắng (1800x1200)",
        description: "Khung 8 ô ảnh khổ ngang 1800x1200.",
        borderColor: "#ffffff",
        borderWidth: 24,
        kind: "solid",
        shotCount: 8,
        photoViewportOrientation: "landscape",
        layoutFamily: "2x4",
        outputWidth: 1800,
        outputHeight: 1200,
    },
    {
        id: "eight-portrait-grid",
        name: "8 Ô Dọc - Grid Trắng (1200x1800)",
        description: "Khung 8 ô ảnh khổ dọc 1200x1800.",
        borderColor: "#ffffff",
        borderWidth: 24,
        kind: "solid",
        shotCount: 8,
        photoViewportOrientation: "portrait",
        layoutFamily: "2x4",
        outputWidth: 1200,
        outputHeight: 1800,
    },
] as const satisfies readonly FrameConfig[];

import { LocalFrameRegistry } from "@/services/frame/local-frame-registry";

export function resolveFrameConfig(frameId: string): FrameConfig {
    if (typeof window !== "undefined") {
        const imported = LocalFrameRegistry.getPublishedRuntimeFrames().find((f) => f.id === frameId);
        if (imported) {
            return imported;
        }
    }
    return frameConfigs.find((frame) => frame.id === frameId) ?? frameConfigs[0];
}
